//! AssumeUTXO trust anchor.
//!
//! These constants commit to a specific UTXO set snapshot. They are the
//! out-of-band trust input that lets us bootstrap a pruned node without
//! validating the chain from genesis. The download source is untrusted —
//! the file is verified against `ASSUMEUTXO_HASH` after download.
//!
//! Generated by `convert_snapshot` from a Bitcoin Core `dumptxoutset` taken
//! at block 943,500.

/// Block height at which the snapshot was taken.
pub const ASSUMEUTXO_HEIGHT: u32 = 943_500;

/// SHA256 hash of the HUTX-format UTXO set, computed by `UtxoSet::compute_hash`.
/// Verified against the file's stored hash on load, then recomputed during
/// insertion to detect tampering of either the body or the header.
pub const ASSUMEUTXO_HASH: [u8; 32] = [
    0x70, 0x55, 0x28, 0xfe, 0x00, 0x33, 0x29, 0xe0,
    0xe6, 0xde, 0x5c, 0x85, 0x4b, 0x83, 0xd5, 0x7b,
    0x0b, 0xad, 0xc2, 0xb9, 0x5b, 0x60, 0xdc, 0x73,
    0xa7, 0xa4, 0x0f, 0x22, 0xf6, 0x2d, 0x13, 0x3e,
];

/// Block hash at the snapshot height (internal byte order, NOT display order).
/// Display order: 00000000000000000001fad98be927b937e32494834f109166fa2ae2e1d1b91a
pub const ASSUMEUTXO_BLOCK_HASH: [u8; 32] = [
    0x1a, 0xb9, 0xd1, 0xe1, 0xe2, 0x2a, 0xfa, 0x66,
    0x91, 0x10, 0x4f, 0x83, 0x94, 0x24, 0xe3, 0x37,
    0xb9, 0x27, 0xe9, 0x8b, 0xd9, 0xfa, 0x01, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
];

/// Public download URL for the gzip-compressed HUTX snapshot.
/// Hosted on Cloudflare R2 (zero egress fees, edge-cached).
pub const SNAPSHOT_DOWNLOAD_URL: &str =
    "https://pub-341db11a2808417d91d4fcabc62a2260.r2.dev/hercules-utxo.hutx.gz";

/// Approximate compressed download size in bytes (for UI progress estimates).
pub const SNAPSHOT_DOWNLOAD_SIZE: u64 = 8_780_302_668;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn block_hash_matches_display() {
        let display = "00000000000000000001fad98be927b937e32494834f109166fa2ae2e1d1b91a";
        let mut from_display = hex::decode(display).unwrap();
        from_display.reverse();
        assert_eq!(&from_display[..], &ASSUMEUTXO_BLOCK_HASH[..]);
    }

    #[test]
    fn utxo_hash_matches_display() {
        let display = "705528fe003329e0e6de5c854b83d57b0badc2b95b60dc73a7a40f22f62d133e";
        let from_display = hex::decode(display).unwrap();
        assert_eq!(&from_display[..], &ASSUMEUTXO_HASH[..]);
    }
}
